### PR TITLE
fix(routes): use directory separator to replace path

### PR DESCRIPTION
**Pull request by WOSHIZHAZHA120**

### CODE REVIEW

**Comment by innocenzi** [comment]
Do you know if `base_path` returns `\\` instead of `/` as well on Windows? Or is my change enough?

**Comment by WOSHIZHAZHA120** [comment]
图片
图片

windows is '\\', linux is '/'
the '\\\\' is json encoded, just replace all '\\' to '/' to resolve

the log context is json encoded, i got a wrong result before

**Comment by innocenzi** [comment]
Ok, I don't have a Windows machine to test on, if you confirm the current solution works, I'll merge 👍

**Comment by WOSHIZHAZHA120** [comment]
OK, all worked now
now is hope package stable and ready for production

**Pull request merged**
