### PR TITLE
feat: support Laravel 10

### PR DESCRIPTION
**Pull request by saibotk**
Added the necessary dependency ranges to the composer.json and added Laravel 10 to the test workflow.

Additionally, fixed the editorconfig to use spaces in yaml (tabs would be incorrect).

### CODE REVIEW

**Comment by saibotk** [comment]
Mhh, I'm unsure about what we want to do regarding the failing tests @innocenzi 

Do we need to have the dependencies locked in the outer scope? If yes we could adjust the workflow to allow updating those dependencies for the testing scenarios.

**Comment by innocenzi** [comment]
I'm not sure yet either but I'll take a look soon, I'll need to spin up a new Laravel project so I'll want to use v10 👍

**Comment by innocenzi** [comment]
Finally. Sorry if you got a lot of notifications lol. Thanks for the PR!

**Comment by saibotk** [comment]
Thats no problem 😉 disabled action notifications a long time ago haha.

Thank you very much for the quick response!

**Pull request merged**
