### PR TITLE
fix(use-property): handle null values

### PR DESCRIPTION
**Pull request by Tofandel**
When using optional data with spatie then that value is given as null in hybridly (and not undefined)

```
props: {
  user: null
}
```

When using `useProperty('user.id')` in this case, getByPath throws an exception that it can't convert `null` to `object`

Instead of erroring we should just return undefined

This error does not happen if user was undefined
```
props: {
  user: undefined
}
```

### CODE REVIEW

**Comment by innocenzi** [comment]
Hey @saibotk, do you think this should be fixed upstream?

**Comment by saibotk** [comment]
Oh jeah definitely. 

@djfhe and I can take a look at this in https://github.com/clickbar/dot-diver directly

**Comment by Tofandel** [comment]
https://github.com/clickbar/dot-diver/blob/main/src/index.ts#L245C14-L245C36

This is because `typeof null === 'object'` I've been bitten so many times by this in javascript

**Comment by saibotk** [comment]
Ohhh i see, thanks for directly contributing to upstream, really appreciate it!
We'll get this in asap.

**Comment by saibotk** [comment]
Info: We've released dot-diver 1.0.5, which fixes this. Huge thanks!

**Comment by innocenzi** [comment]
Thank you both! Updated the PR to upgrade dot-diver 👍

**Comment by saibotk** [comment]
Nice, oh what happened with the Global props type, seems like we changed something there that needs adjustment :face_with_spiral_eyes:

**Comment by Tofandel** [comment]
From what I see it's the change I made from `never` to `string | number | symbol`

For some very strange reason 

`
GlobalHybridlyProperties {
	[key: string | number]: Property
}
`

Is not assignable to

`Record<string | number | symbol, unknown>`

**Comment by Tofandel** [comment]
Ok, we just need to change it to `type SafeObject = Record<any, unknown>` and it fixes it without causing type issues in the lib, I really don't know why ts can't match the types because they definitely are compatible

**Pull request merged**
