### PR TITLE
fix(vite): revert skip typescript types generation on build

### PR DESCRIPTION
**Pull request by johanmolen**
At the moment `npm run build` does not generate `hybridly.d.ts` which can give errors if you run for example `vue-tsc` after.

The reason we disabled it on build was that `laravel-typescript-transformer` is a dev dependency.

### CODE REVIEW

**Comment by johanmolen** [comment]
I guess this does not solve the problem entirely because `GlobalHybridlyProperties` extends `App.Data.SharedData` which is not generated. (if dev dependencies are not installed)

**Comment by innocenzi** [comment]
Indeed, at the end of the day we might want `laravel-typescript-transformer` to be an actual dependency

**Comment by johanmolen** [comment]
I guess so, I don't see any downsides of it.

**Comment by innocenzi** [comment]
Thanks for the PR anyway!

**Pull request merged**
