### PR TITLE
Fix deprecation message caused by `cachedRefinements`

### PR DESCRIPTION
**Pull request by tomykho**

### CODE REVIEW

**Comment by innocenzi** [comment]
Sorry, didn't see the PR before fixing it myself 😔

**Comment by tomykho** [comment]
It's okay, are you going to release it together with v0.7.15 anytime soon?

**Comment by innocenzi** [comment]
It wasn't planned that early, do you need that fix?

**Comment by tomykho** [comment]
Not urgent, you can take your time to plan the release.
It just keep spamming non stop to my Cloudwatch logs everytime users visiting the site with tables.
I will use this commit https://github.com/hybridly/hybridly/commit/1ff3b69654e0dacff7ac87632a2e0bbad2286651 for now in composer.json and I will change it after you released v0.7.15.

**Pull request closed without merging**
