### PR TITLE
fix(routing): avoid matching unrelated routes using `current`

### PR DESCRIPTION
**Pull request by nhedger**
TBD

### CODE REVIEW

**Review by saibotk — APPROVED** [review]
Looks good to me, seems like I missed this when implementing this.

Reference:
Ziggy also does this:
https://github.com/tighten/ziggy/blob/c53c891ede223c53046c6a8f7635a86eb017fe2a/src/js/Router.js#L122

**Comment by innocenzi** [comment]
What happens if you change the order of `baz.nested` and `baz` in the fixtures? Does the test still work?

**Comment by nhedger** [comment]
If by changing the order you mean the following, then yes, the test still passes.

```json
"baz.nested": {
    "domain": null,
    "method": ["GET", "HEAD"],
    "uri": "baz/nested",
    "name": "baz.nested",
    "bindings": [],
    "wheres": []
},
"baz": {
    "domain": null,
    "method": ["GET", "HEAD"],
    "uri": "baz",
    "name": "baz",
    "bindings": [],
    "wheres": []
},
```

**Comment by innocenzi** [comment]
Awesome, thank you!

**Pull request merged**
