### PR TITLE
feat(testing): add `TestFileViewFinder` to support domains

### PR DESCRIPTION
**Pull request by nickarellano**
This pull request is to add a custom `TestFileViewFinder` in order to allow for assertHybridView() to utilize the domain syntax for views.

### CODE REVIEW

**Comment by nickarellano** [comment]
Not thinking, I should have named this something more like `HybridlyFileViewFinder`

**Comment by innocenzi** [comment]
Awesome! I think the current name is perfectly fine. The `domains` value should be configurable though, because it also is configurable in `vite.config.ts`

**Comment by nickarellano** [comment]
resolvePageComponent also has domains hardcoded, am I missing where there is an override?

**Comment by innocenzi** [comment]
Aah, you're right. Woops. I guess I'll refactor that later to take into account the options given to the Vite plugin.

**Comment by nickarellano** [comment]
I just realized I didn't branch off of `0.x` for this PR.

**Pull request merged**
